import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

const Todo: NextPage = () => {
    const [todoList, setTodoList] = useState([
        'Go for a run',
        'Attend that meeting',
        'Do coding of a project',
        'Have food',
        'Go to bed too late'
      ])
      const [newTodoItem, setNewTodoItem] = useState('')
      const addTodoItem = (): void => {
    
      const newTodoList = todoList.concat(newTodoItem)
    setTodoList(newTodoList)
  };
  const markTodoItem = (markedItem: string, isMarked: boolean) : void => {
    if (isMarked) {
        // Create a new version of the list filtering out the marked item, then
        // set the todo list state variable to the new list.
        const newTodoList = todoList.filter(e => e !== markedItem)
        setTodoList(newTodoList)
      }
    }
  
    // Define the page's HTML structure. This includes a mapping function to
    // loop through the todo list items and create an li element for each with
    // the todo item text and a checkbox for marking it complete.
    return (
      <div className={styles.container}>
        <Head>
          <title>Example Next App | Todo List</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            My Daily Todo List
          </h1>
          <div className={styles.grid}>
            <div className={styles.card}>
              <h3>Click the box to Remove</h3>
              <ol>
                {todoList.map((todoItem) => (
                  <li key={todoItem}>
                    {/* click on the box to delete */}
                    <input type="checkbox" value="x"onChange={ (e) => markTodoItem(todoItem, e.target.checked) } />
                    <span>{todoItem}</span>
                  </li>
                ))}
              </ol>
            </div>
            <div className={styles.card}>
              <h2>Add New Item</h2>
                <p>
                  <input type="text" onChange={ (e) => { setNewTodoItem(e.target.value) } } />
                  <button onClick={addTodoItem}>Add</button>
                </p>
            </div>
          </div>
        </main>
      </div>
    )
  }
  
  // Export the page for processing and display.
  export default Todo